"""Generate the worked-examples TeX fragment from registered JSON
(plan §12: prose numbers regenerate; nothing hand-typed)."""
from __future__ import annotations

import json
from pathlib import Path

from .paths import DRIVE_ROOT, REPORTS


def _esc(text: str) -> str:
    for a, b in (("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"),
                 ("_", "\\_"), ("#", "\\#"), ("$", "\\$")):
        text = text.replace(a, b)
    return text


def build(lane_dir: Path, out: Path) -> Path:
    ps = json.loads((lane_dir / "probe_swap_qwen.json").read_text())
    fg = json.loads((lane_dir / "flexible_generalization_qwen.json").read_text())
    lines: list[str] = ["% AUTO-GENERATED by report_examples — do not edit"]

    wins = [r for r in ps["rows"] if r.get("top1_success")]
    already = [r for r in wins if r["swap_answer_rank_before"] == 1]
    lines.append(
        "\\newcommand{\\qwpswinstable}{%\n"
        "\\begin{tabular}{llrrl}\\toprule\n"
        "item & category & \\multicolumn{2}{c}{swap-answer rank} & model output\\\\\n"
        " & & before & after & after swap\\\\\\midrule\n"
    )
    for r in sorted(wins, key=lambda x: -x["swap_answer_rank_before"])[:8]:
        lines.append(
            f"\\texttt{{{_esc(r['name'])}}} & {_esc(r['category'])} & "
            f"{r['swap_answer_rank_before']} & 1 & "
            f"\\texttt{{{_esc(r['top1_token'].strip())}}}\\\\\n")
    lines.append("\\bottomrule\\end{tabular}}")
    lines.append(f"\\newcommand{{\\qwpsnwins}}{{{len(wins)}}}")
    lines.append(f"\\newcommand{{\\qwpsnwinstrivial}}{{{len(already)}}}")

    near = [r for r in ps["rows"]
            if r.get("state") == "EXECUTED" and not r["top1_success"]
            and r.get("swap_answer_rank_after") is not None
            and r["swap_answer_rank_after"] <= 5]
    lines.append(f"\\newcommand{{\\qwpsnnear}}{{{len(near)}}}")

    fg_wins = []
    for c in fg["categories"]:
        for cell in c["cells"]:
            a1 = cell.get("alpha1", {})
            if a1.get("state") == "EXECUTED" and a1.get("top1"):
                fg_wins.append((c["category"], cell["function"],
                                cell["source_arg"], cell["target_arg"],
                                cell["rank_before"], a1["top1_token"]))
    lines.append(
        "\\newcommand{\\qwfgwinstable}{%\n"
        "\\begin{tabular}{lllrl}\\toprule\n"
        "category & function & swap & rank before & output\\\\\\midrule\n")
    for cat, fn, s, t, before, out_tok in sorted(fg_wins, key=lambda x: -x[4])[:8]:
        lines.append(
            f"{_esc(cat)} & {_esc(fn)} & {_esc(s)}$\\to${_esc(t)} & "
            f"{before} & \\texttt{{{_esc(out_tok.strip())}}}\\\\\n")
    lines.append("\\bottomrule\\end{tabular}}")
    lines.append(f"\\newcommand{{\\qwfgnwins}}{{{len(fg_wins)}}}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    return out


if __name__ == "__main__":
    path = build(DRIVE_ROOT / "qwen_lane", REPORTS / "tex" / "examples.tex")
    print("wrote", path)
