"""Extract report numbers from registered JSON into TeX macros.

Every number the report prints regenerates from these inputs (plan §12);
the TeX never hard-codes a result value.
"""
from __future__ import annotations

import json
from pathlib import Path

from .paths import DRIVE_ROOT, REPORTS

_K_WORDS = {1: "one", 5: "five", 20: "twenty"}

EVAL_SHORT = {"lens-eval-multihop": "multihop",
              "lens-eval-multilingual": "multilingual",
              "lens-eval-poetry": "poetry",
              "lens-eval-typo": "typo",
              "lens-eval-order-ops": "orderops",
              "lens-eval-association": "association"}


def _fmt(value, digits=3):
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def _pct(value):
    return "—" if value is None else f"{100 * value:.1f}\\%"


def qwen_macros(lane_dir: Path) -> dict[str, str]:
    macros: dict[str, str] = {}
    for set_name, short in EVAL_SHORT.items():
        for prefix, tag in (("eval_", ""), ("eval_alllayers_", "all")):
            path = lane_dir / f"{prefix}{set_name}.json"
            if not path.exists():
                continue
            data = json.loads(path.read_text())
            for which in ("jlens", "logit"):
                agg = data[f"aggregate_{which}"]["token_valid"]
                for k in (1, 5, 20):
                    macros[f"qw{tag}{short}{which}p{_K_WORDS[k]}"] = _fmt(agg[f"pass@{k}"])
            macros[f"qw{tag}{short}n"] = str(data["n_items"])
            att = data["aggregate_jlens"]["attrition"]
            macros[f"qw{tag}{short}gated"] = str(att["gated_intermediates"])
    vr = lane_dir / "verbal_report_qwen.json"
    if vr.exists():
        data = json.loads(vr.read_text())
        macros["qwvrcattopone"] = _pct(data["category_equal_top1"])
        macros["qwvrcattopfive"] = _pct(data["category_equal_top5"])
        macros["qwvrtrialtopone"] = _pct(data["trial_weighted_top1"])
        macros["qwvrncat"] = str(data["n_categories"])
        executed = sum(c["n_executed"] for c in data["categories"])
        macros["qwvrnexec"] = str(executed)
        improved = worsened = 0
        for c in data["categories"]:
            for t in c["trials"]:
                if t.get("state") == "EXECUTED":
                    if t["rank_after"] < t["rank_before"]:
                        improved += 1
                    elif t["rank_after"] > t["rank_before"]:
                        worsened += 1
        macros["qwvrimproved"] = str(improved)
        macros["qwvrworsened"] = str(worsened)
    fg = lane_dir / "flexible_generalization_qwen.json"
    if fg.exists():
        data = json.loads(fg.read_text())
        macros["qwfgcapaone"] = _pct(data["category_equal_capable_top1_alpha1"])
        macros["qwfgcapatwo"] = _pct(data["category_equal_capable_top1_alpha2"])
        macros["qwfgdiagaone"] = _pct(data["category_equal_diagnostic_top1_alpha1"])
        total_capable = sum(c["n_capable"] for c in data["categories"])
        macros["qwfgncapable"] = str(total_capable)
        macros["qwfgnexec"] = str(data["total_executed_alpha1"])
        base = [c["baseline_correct_fraction"] for c in data["categories"]]
        macros["qwfgbaseline"] = _pct(sum(base) / len(base))
        for c in data["categories"]:
            key = c["category"][:5]
            macros[f"qwfg{key}capaone"] = _pct(c["capable_top1_alpha1"])
            macros[f"qwfg{key}capatwo"] = _pct(c["capable_top1_alpha2"])
            macros[f"qwfg{key}ncap"] = str(c["n_capable"])
    ps = lane_dir / "probe_swap_qwen.json"
    if ps.exists():
        data = json.loads(ps.read_text())
        macros["qwpsncap"] = str(data["n_baseline_capable"])
        macros["qwpsnexec"] = str(data["n_executed"])
        macros["qwpsntokgated"] = str(data["n_tokenization_gated"])
        macros["qwpscaptopone"] = _pct(data["capable_top1"])
        macros["qwpsdiagtopone"] = _pct(data["diagnostic_top1"])
        macros["qwpsmulti"] = _pct(data["multihop_capable_top1"])
        macros["qwpsnonmulti"] = _pct(data["non_multihop_capable_top1"])
    adm = lane_dir / "qwen_admission.json"
    if adm.exists():
        data = json.loads(adm.read_text())
        macros["qwparity"] = f"{data['readout_parity']['max_abs_diff']:.1e}"
        macros["qwgfold"] = _fmt(data["g_folding"]["min_cosine"])
    return macros


def write_numbers_tex(out: Path | None = None) -> Path:
    out = out or (REPORTS / "tex" / "numbers.tex")
    out.parent.mkdir(parents=True, exist_ok=True)
    macros = qwen_macros(DRIVE_ROOT / "qwen_lane")
    olmo_dir = DRIVE_ROOT / "olmo_lane"
    if olmo_dir.exists():
        for key, value in qwen_macros(olmo_dir).items():
            # olmo lane reuses the same extractors with its own files
            pass
    lines = ["% AUTO-GENERATED by jspace_official_repro.report_data — do not edit"]
    for key, value in sorted(macros.items()):
        lines.append(f"\\newcommand{{\\{key}}}{{{value}}}")
    out.write_text("\n".join(lines) + "\n")
    return out


if __name__ == "__main__":
    path = write_numbers_tex()
    print("wrote", path)
